Repository googleapis/python-texttospeech, pull requests merged in 2021-04, with the labels that each got.

#118 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: texttospeech, cla: yes, context: full

#117 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .pre-commit-config.yaml
  docs/conf.py
  owlbot.py
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes

#119 chore: prevent normalization of semver versioning
  setup.py
Labels: api: texttospeech, cla: yes

#128 chore(revert): revert preventing normalization
  setup.py
Labels: api: texttospeech, cla: yes
